import fs from 'node:fs';
import ts from 'typescript';
const source = fs.readFileSync('../careshift-sos-work/dist/app.js','utf8');
const ast=ts.createSourceFile('old.js',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const alias={class:'className',for:'htmlFor',tabindex:'tabIndex',viewbox:'viewBox','stroke-width':'strokeWidth','stroke-linecap':'strokeLinecap','stroke-linejoin':'strokeLinejoin'};
function html(text,expr=[]){
 const val=s=>{const parts=s.split(/(__EXPR\d+__)/g).filter(Boolean).map(p=>/^__EXPR/.test(p)?`(${expr[+p.match(/\d+/)[0]]})`:JSON.stringify(p));return parts.join('+')||'""'};
 const root={children:[]},stack=[root];
 const tokens=text.match(/<!--[\s\S]*?-->|<[^>]+>|[^<]+/g)||[];
 for(const token of tokens){if(token.startsWith('<!--'))continue;if(token.startsWith('</')){stack.pop();continue}if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const attrs={};for(const m of token.slice(tag.length+1).matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s/>]+)))?/g)){let k=alias[m[1]]||m[1];if(k==='value'&&tag!=='option')k='defaultValue';if(k==='checked')k='defaultChecked';const v=m[2]??m[3]??m[4];attrs[k]=v===undefined?'true':k==='style'?`css(${val(v)})`:val(v)}const node={tag,attrs,children:[]};stack.at(-1).children.push(node);if(!/\/$/.test(token.slice(0,-1))&&!['input','br','hr','img','meta','link'].includes(tag))stack.push(node)}else{for(const part of token.split(/(__EXPR\d+__)/g)){if(part)stack.at(-1).children.push(/^__EXPR\d+__$/.test(part)?{expr:expr[+part.match(/\d+/)[0]]}:{text:part})}}}
 function out(n){if(n.expr!==undefined)return `(${n.expr})`;if(n.text!==undefined)return JSON.stringify(n.text);if(n.tag==='select'){const selected=n.children.find(c=>c.attrs?.selected);if(selected)n.attrs.defaultValue=selected.attrs.value||selected.children.map(out).join('+');}if(n.tag==='textarea'&&n.children.length){n.attrs.defaultValue=n.children.map(out).join('+');n.children=[];}delete n.attrs.selected;return `careElement(${JSON.stringify(n.tag)},{${Object.entries(n.attrs).map(([k,v])=>JSON.stringify(k)+':'+v).join(',')}},${n.children.map(out).join(',')})`.replace(/,\)$/ ,')')}
 return root.children.length===1?out(root.children[0]):`careElement(Fragment,null,${root.children.map(out).join(',')})`;
}
function convert(node){if(ts.isStringLiteral(node)||ts.isNoSubstitutionTemplateLiteral(node)){return /^\s*</.test(node.text)?html(node.text):node.getText(ast)}if(ts.isTemplateExpression(node)&&(/^\s*</.test(node.head.text)||node.head.text===''&&node.templateSpans.every(s=>s.literal.text===''))){const ex=[];let s=node.head.text;for(const span of node.templateSpans){s+=`__EXPR${ex.length}__`+span.literal.text;ex.push(convert(span.expression))}return html(s,ex)}let s=node.getText(ast),base=node.getStart(ast);const edits=[];node.forEachChild(c=>{const t=convert(c);if(t!==c.getText(ast))edits.push([c.getStart(ast)-base,c.end-base,t])});for(const [a,b,t] of edits.reverse())s=s.slice(0,a)+t+s.slice(b);return s.replace(/\.join\(''\)/g,'')}
const helpers=['statusBadge','sosButton','quickIcon','primaryFamily','familyPage','familyCard','activeCare','matchingView','nurseCard','requestNotification','rosterTable','scheduleView','profileStub','requestTable','hospitalTable','accountTable'];
const data=[],views=[];
for(const node of ast.statements){if(ts.isVariableStatement(node)){const name=node.declarationList.declarations[0].name.getText(ast);if(['icons','roles','nurses','roster','familyContacts'].includes(name))data.push(convert(node).replace('let familyContacts=','const initialFamily='));if(name==='views')views.push(convert(node));}if(ts.isFunctionDeclaration(node)&&helpers.includes(node.name.text))views.push(convert(node))}
const old=fs.readFileSync('../careshift-sos-work/dist/index.html','utf8');
let body=old.split('<body>')[1].split('<script')[0];
body=body.replace('<nav id="sideNav"></nav>','<nav id="sideNav">__EXPR0__</nav>').replace('<section id="appContent" class="app-content" aria-live="polite"></section>','<section id="appContent" class="app-content" aria-live="polite">__EXPR1__</section>').replace('<div class="toast-stack" id="toastStack" aria-live="polite"></div>','<div class="toast-stack" id="toastStack" aria-live="polite">__EXPR2__</div>');
for(const [id,v]of Object.entries({roleName:'r.label',roleOrg:'r.org',roleAvatar:'r.avatar',profileName:'r.profile',profileMeta:'r.meta',crumbRole:'r.app',crumbPage:'currentTitle',sosFamilyLabel:'familyLabel'})){body=body.replace(new RegExp(`(<[^>]+id="${id}"[^>]*>)[^<]*(</[^>]+>)`),'$1__DYNAMIC_'+v+'__$2')}
body=body.replace('Tiếp tục <svg','__DYNAMIC_wizardLabel__ <svg');
const shellExpr=['navigation','content','toastContent'];body=body.replace(/__DYNAMIC_(.*?)__/g,(_,x)=>`__EXPR${shellExpr.push(x)-1}__`);
body=body.replace('<div id="requestReview"','<div id="requestReview"');body=body.replace('<div class="review-card" id="requestReview"></div>','<div class="review-card" id="requestReview">__EXPR'+(shellExpr.push('review')-1)+'__</div>');body=body.replace('<div id="nurseDetailContent"></div>','<div id="nurseDetailContent">__EXPR'+(shellExpr.push('nurseDetail')-1)+'__</div>');
fs.writeFileSync('app/care-views.jsx',`import React,{createElement as careElement,Fragment} from 'react';\nconst css=s=>Object.fromEntries(s.split(';').filter(Boolean).map(x=>{const i=x.indexOf(':');return[x.slice(0,i).trim().replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),x.slice(i+1).trim()]}));\n${data.join('\n')}\nexport {roles,nurses,initialFamily,icons};\nexport function buildViews(state,familyContacts){const pageTitle=()=>{};${views.join('\n')}\nreturn views;}\nexport function Shell({navigation,content,toastContent,r,currentTitle,familyLabel,review,nurseDetail,wizardLabel}){return ${html(body,shellExpr)}}\n`);
for(const name of ['styles.css','mobile-nav.css','family-link.css'])fs.copyFileSync('../careshift-sos-work/dist/'+name,'app/'+name);
fs.writeFileSync('app/globals.css','@import "./styles.css";\n@import "./mobile-nav.css";\n@import "./family-link.css";\n');
console.log('Converted original templates to React element components.');
